# Generated by Django 4.2.30 on 2026-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='url',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.CharField(blank=True, help_text='Ex: Python, Django, React', max_length=300),
        ),
        migrations.AddField(
            model_name='projeto',
            name='url_site',
            field=models.URLField(blank=True, verbose_name='URL do site'),
        ),
    ]
