# Generated by Django 4.2.30 on 2026-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_projeto_options_remove_projeto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem_url',
            field=models.URLField(blank=True, default='https://placehold.co/600x400/0A0A0A/00FF41?text=Hacker+Project', verbose_name='URL da imagem'),
        ),
    ]
